// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.controllers;

import com.flightreservation.flightreservation.domains.Flight;
import com.flightreservation.flightreservation.repositories.FlightRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.ui.ModelMap;

public class FlightController_showAddFlightPage_d59f74fc01_Test {

    @InjectMocks
    FlightController flightController;

    @Mock
    FlightRepository flightRepository;

    @Mock
    ModelMap modelMap;

    @Test
    public void testShowAddFlightPage() {
        MockitoAnnotations.initMocks(this);
        String result = flightController.showAddFlightPage();
        Assertions.assertEquals("flights/addFlight", result);
    }

    @Test
    public void testShowAddFlightPage_Failure() {
        MockitoAnnotations.initMocks(this);
        String result = flightController.showAddFlightPage();
        Assertions.assertNotEquals("flights/wrongPath", result);
    }
}
