// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.controllers;

import org.junit.jupiter.api.Test;
import org.springframework.ui.Model;
import org.springframework.beans.factory.annotation.Autowired;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

public class FlightController_showAddFlightPage_d59f74fc01_Test {

    @Autowired
    FlightController flightController;

    @Test
    public void testShowAddFlightPage_Success() {
        String actual = flightController.showAddFlightPage();
        String expected = "flights/addFlight";
        assertEquals(expected, actual);
    }

    @Test
    public void testShowAddFlightPage_Failure() {
        FlightController mockedFlightController = mock(FlightController.class);
        String actual = mockedFlightController.showAddFlightPage();
        String expected = "flights/addFlight";
        assertEquals(expected, actual);
    }
}
