// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.controllers;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class FlightController_showAddFlightPage_36f1be0ed6_Test {

    @InjectMocks
    private FlightController flightController;

    @Test
    public void testShowAddFlightPage_Success() {
        String viewName = flightController.showAddFlightPage();
        assertEquals("flights/addFlight", viewName, "The view name returned by the method does not match the expected view name.");
    }

    @Test
    public void testShowAddFlightPage_Failure() {
        String viewName = flightController.showAddFlightPage();
        assertEquals("flights/addFlight", viewName, "The view name returned by the method does not match the expected view name.");
    }
}
