// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.controllers;

import com.flightreservation.flightreservation.domains.Flight;
import com.flightreservation.flightreservation.domains.Reservation;
import com.flightreservation.flightreservation.dto.ReservationRequest;
import com.flightreservation.flightreservation.exceptions.FlightNotFound;
import com.flightreservation.flightreservation.repositories.FlightRepository;
import com.flightreservation.flightreservation.services.ReservationService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;
import org.springframework.ui.ModelMap;

public class ReservationController_completeReservation_c517119304_Test {

    private ReservationService reservationService;
    private ReservationController reservationController;
    private ModelMap modelMap;

    @BeforeEach
    public void setup() {
        reservationService = mock(ReservationService.class);
        reservationController = new ReservationController(reservationService);
        modelMap = new ModelMap();
    }

    @Test
    public void testCompleteReservationSuccess() {
        ReservationRequest reservationRequest = new ReservationRequest();
        Reservation reservation = new Reservation();
        reservation.setId(1L);

        when(reservationService.bookFlight(any(ReservationRequest.class))).thenReturn(reservation);

        String result = reservationController.completeReservation(reservationRequest, modelMap);

        assertEquals("reservation/reservationConfirmation", result);
        assertEquals("Reservation created successfully and the reservation id is 1", modelMap.get("msg"));
    }

    @Test
    public void testCompleteReservationFailure() {
        ReservationRequest reservationRequest = new ReservationRequest();

        when(reservationService.bookFlight(any(ReservationRequest.class))).thenThrow(new FlightNotFound("Flight not found"));

        try {
            reservationController.completeReservation(reservationRequest, modelMap);
        } catch (FlightNotFound e) {
            assertEquals("Flight not found", e.getMessage());
        }
    }
}
