// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.controllers;

import com.flightreservation.flightreservation.domains.User;
import com.flightreservation.flightreservation.exceptions.UserNotFound;
import com.flightreservation.flightreservation.repositories.UserRepository;
import com.flightreservation.flightreservation.services.SecurityService;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.ui.ModelMap;

import java.util.Optional;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class UserController_login_21e86cf89a_Test {

    @InjectMocks
    UserController userController;

    @Mock
    UserRepository userRepository;

    @Mock
    SecurityService securityService;

    private String email;
    private String password;
    private ModelMap modelMap;

    @Before
    public void setUp() {
        email = "test@test.com";
        password = "password";
        modelMap = new ModelMap();
    }

    @Test
    public void login_UserExists_LoginSuccess() {
        when(userRepository.findByEmail(email)).thenReturn(Optional.of(new User()));
        when(securityService.login(email, password)).thenReturn(true);

        String result = userController.login(email, password, modelMap);

        assertEquals("flights/findFlights", result);
        assertEquals("Successfully logged in", modelMap.get("msg"));
    }

    @Test(expected = UserNotFound.class)
    public void login_UserDoesNotExist_ThrowsUserNotFound() {
        when(userRepository.findByEmail(email)).thenReturn(Optional.empty());

        userController.login(email, password, modelMap);
    }

    @Test
    public void login_InvalidCredentials_ReturnsLogin() {
        when(userRepository.findByEmail(email)).thenReturn(Optional.of(new User()));
        when(securityService.login(email, password)).thenReturn(false);

        String result = userController.login(email, password, modelMap);

        assertEquals("login/login", result);
        assertEquals("Invalid username or password", modelMap.get("msg"));
    }
}
