// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.security.config;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import static org.junit.jupiter.api.Assertions.*;

public class WebSecurityConfig_bCryptPasswordEncoder_f71e234ede_Test {

    private WebSecurityConfig webSecurityConfig;

    @BeforeEach
    public void setUp() {
        webSecurityConfig = new WebSecurityConfig();
    }

    @Test
    public void testBCryptPasswordEncoder_Success() {
        BCryptPasswordEncoder encoder = webSecurityConfig.bCryptPasswordEncoder();
        assertNotNull(encoder);

        String rawPassword = "password123";
        String encodedPassword = encoder.encode(rawPassword);

        assertTrue(encoder.matches(rawPassword, encodedPassword));
    }

    @Test
    public void testBCryptPasswordEncoder_Failure() {
        BCryptPasswordEncoder encoder = webSecurityConfig.bCryptPasswordEncoder();
        assertNotNull(encoder);

        String rawPassword = "password123";
        String wrongRawPassword = "wrongPassword";
        String encodedPassword = encoder.encode(rawPassword);

        assertFalse(encoder.matches(wrongRawPassword, encodedPassword));
    }
}
