// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

@MappedSuperclass
public class AbstractEntity_getId_ba349b1eff_Test {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @InjectMocks
    private AbstractEntity abstractEntity;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    public Long getId() {
        return id;
    }

    @Test
    public void testGetIdSuccess() {
        Long expectedId = 1L;
        id = expectedId;
        Long actualId = getId();
        assertEquals(expectedId, actualId, "The expected ID does not match the actual ID");
    }

    @Test
    public void testGetIdWhenIdIsNull() {
        id = null;
        Long actualId = getId();
        assertNull(actualId, "The ID should be null");
    }
}
