// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class AbstractEntity_setId_04a8e16b7c_Test {

    private AbstractEntity abstractEntity;

    @BeforeEach
    public void setup() {
        abstractEntity = new AbstractEntity();
    }

    @Test
    public void testSetId() {
        Long expectedId = 123L;
        abstractEntity.setId(expectedId);
        assertEquals(expectedId, abstractEntity.getId(), "The id should be set correctly");
    }

    @Test
    public void testSetId_Null() {
        abstractEntity.setId(null);
        assertEquals(null, abstractEntity.getId(), "The id should be null");
    }
}
