// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import static org.mockito.Mockito.when;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class AbstractEntity_getId_eb19b6a6d6_Test {

    private AbstractEntity abstractEntity;
    private AbstractEntity abstractEntityMock;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @BeforeEach
    public void setup() {
        abstractEntity = new AbstractEntity();
        abstractEntityMock = Mockito.mock(AbstractEntity.class);
    }

    @Test
    public void testGetIdSuccess() {
        Long expectedId = 1L;
        when(abstractEntityMock.getId()).thenReturn(expectedId);

        Long actualId = abstractEntityMock.getId();

        Assertions.assertEquals(expectedId, actualId, "The expected ID does not match the actual ID.");
    }

    @Test
    public void testGetIdFailure() {
        Long unexpectedId = 2L;
        when(abstractEntityMock.getId()).thenReturn(1L);

        Long actualId = abstractEntityMock.getId();

        Assertions.assertNotEquals(unexpectedId, actualId, "The unexpected ID should not match the actual ID.");
    }
}
