// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_setDepartureCity_0667311b63_Test {

    @Test
    public void testSetDepartureCity() {
        Flight flight = new Flight();
        String departureCity = "New York";
        flight.setDepartureCity(departureCity);
        assertEquals(departureCity, flight.getDepartureCity());
    }

    @Test
    public void testSetDepartureCityNull() {
        Flight flight = new Flight();
        String departureCity = null;
        flight.setDepartureCity(departureCity);
        assertEquals(departureCity, flight.getDepartureCity());
    }
}
