// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import java.sql.Timestamp;
import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_toString_2393b88875_Test {

    private Flight flight;

    @BeforeEach
    public void setUp() {
        flight = new Flight();
    }

    @Test
    public void testToString() {
        flight.setFlightNumber("FN1234");
        flight.setOperatingAirlines("Airline1");
        flight.setDepartureCity("CityA");
        flight.setArrivalCity("CityB");
        flight.setDateOfDeparture(new Date(2022, 12, 1));
        flight.setEstimatedDepartureTime(new Timestamp(System.currentTimeMillis()));

        String expected = "Flight{" +
                "flightNumber='FN1234'" +
                ", operatingAirlines='Airline1'" +
                ", departureCity='CityA'" +
                ", arrivalCity='CityB'" +
                ", dateOfDeparture=" + new Date(2022, 12, 1) +
                ", estimatedDepartureTime=" + flight.getEstimatedDepartureTime() +
                '}';

        assertEquals(expected, flight.toString());
    }

    @Test
    public void testToStringWithNullValues() {
        flight.setFlightNumber(null);
        flight.setOperatingAirlines(null);
        flight.setDepartureCity(null);
        flight.setArrivalCity(null);
        flight.setDateOfDeparture(null);
        flight.setEstimatedDepartureTime(null);

        String expected = "Flight{" +
                "flightNumber='null'" +
                ", operatingAirlines='null'" +
                ", departureCity='null'" +
                ", arrivalCity='null'" +
                ", dateOfDeparture=null" +
                ", estimatedDepartureTime=null" +
                '}';

        assertEquals(expected, flight.toString());
    }
}
