// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_getDepartureCity_872304df93_Test {

    @InjectMocks
    private Flight flight;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetDepartureCity() {
        String expectedCity = "New York";
        flight.setDepartureCity(expectedCity);
        String actualCity = flight.getDepartureCity();
        assertEquals(expectedCity, actualCity, "Departure city should match the set value");
    }

    @Test
    public void testGetDepartureCityWhenNoCitySet() {
        String actualCity = flight.getDepartureCity();
        assertEquals(null, actualCity, "Departure city should be null when no city is set");
    }
}
