// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Flight_setDepartureCity_0fea9c2cf9_Test {

    private Flight flight;

    @BeforeEach
    void setUp() {
        flight = new Flight();
    }

    @Test
    void testSetDepartureCity_validCity() {
        String validCity = "New York";
        flight.setDepartureCity(validCity);
        assertEquals(validCity, flight.getDepartureCity());
    }

    @Test
    void testSetDepartureCity_emptyCity() {
        String emptyCity = "";
        flight.setDepartureCity(emptyCity);
        assertEquals(emptyCity, flight.getDepartureCity());
    }

    @Test
    void testSetDepartureCity_nullCity() {
        String nullCity = null;
        flight.setDepartureCity(nullCity);
        assertEquals(nullCity, flight.getDepartureCity());
    }
}
