// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import java.sql.Timestamp;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_getEstimatedDepartureTime_b20777989e_Test {

    @InjectMocks
    private Flight flight;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetEstimatedDepartureTime() {
        Timestamp timestamp = new Timestamp(new Date().getTime());
        flight.setEstimatedDepartureTime(timestamp);

        Timestamp result = flight.getEstimatedDepartureTime();

        assertEquals(timestamp, result, "The expected and actual departure times should match");
    }

    @Test
    public void testGetEstimatedDepartureTime_null() {
        flight.setEstimatedDepartureTime(null);

        Timestamp result = flight.getEstimatedDepartureTime();

        assertEquals(null, result, "The expected and actual departure times should match when both are null");
    }
}
