// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import javax.persistence.Entity;
import java.sql.Timestamp;
import java.util.Date;

@SpringBootTest
public class Flight_getDateOfDeparture_cae20eaccb_Test {

    @Test
    public void testGetDateOfDeparture_Success() {
        // Mock the Flight entity
        Flight flight = Mockito.mock(Flight.class);
        Date expectedDate = new Timestamp(System.currentTimeMillis());

        // TODO: Change the return value to the expected date of departure
        when(flight.getDateOfDeparture()).thenReturn(expectedDate);

        // Call the method under test
        Date actualDate = flight.getDateOfDeparture();

        // Assert that the expected and actual values are the same
        assertEquals(expectedDate, actualDate);
    }

    @Test
    public void testGetDateOfDeparture_Null() {
        // Mock the Flight entity
        Flight flight = Mockito.mock(Flight.class);

        // When getDateOfDeparture is called, return null
        when(flight.getDateOfDeparture()).thenReturn(null);

        // Call the method under test
        Date actualDate = flight.getDateOfDeparture();

        // Assert that the actual value is null
        assertEquals(null, actualDate);
    }
}
