// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import java.sql.Timestamp;
import java.util.Date;

public class Flight_setEstimatedDepartureTime_783734b631_Test {

    private Flight flight;

    @BeforeEach
    public void setUp() {
        flight = new Flight();
    }

    @Test
    public void testSetEstimatedDepartureTime_whenTimeIsSet_thenCorrectTimeIsReturned() {
        Timestamp timestamp = new Timestamp(new Date().getTime());
        flight.setEstimatedDepartureTime(timestamp);

        assertEquals(timestamp, flight.getEstimatedDepartureTime());
    }

    @Test
    public void testSetEstimatedDepartureTime_whenNullTimeIsSet_thenNullIsReturned() {
        flight.setEstimatedDepartureTime(null);

        assertEquals(null, flight.getEstimatedDepartureTime());
    }
}
