// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import java.sql.Timestamp;
import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

@Entity
public class Flight_setDateOfDeparture_da55158441_Test {

    private Flight flight;

    @BeforeEach
    public void setup() {
        flight = new Flight();
    }

    @Test
    public void testSetDateOfDeparture_validDate() {
        Date date = new Timestamp(System.currentTimeMillis());
        flight.setDateOfDeparture(date);
        assertEquals(date, flight.getDateOfDeparture());
    }

    @Test
    public void testSetDateOfDeparture_nullDate() {
        flight.setDateOfDeparture(null);
        assertEquals(null, flight.getDateOfDeparture());
    }
}
