// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Date;

import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
@SpringBootTest
public class Flight_setDateOfDeparture_63ab78ac82_Test {

    @Mock
    private Flight flight;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetDateOfDeparture() {
        Date date = new Date();
        flight.setDateOfDeparture(date);
        assertEquals(date, flight.getDateOfDeparture());
    }

    @Test
    public void testSetDateOfDeparture_NullDate() {
        Date date = null;
        flight.setDateOfDeparture(date);
        assertEquals(date, flight.getDateOfDeparture());
    }
}
