// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.Assert.assertEquals;

public class Flight_setArrivalCity_ad33fe104d_Test {

    @InjectMocks
    Flight flight;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetArrivalCitySuccess() {
        String arrivalCity = "New York";
        flight.setArrivalCity(arrivalCity);
        assertEquals("Arrival city should be New York", arrivalCity, flight.getArrivalCity());
    }

    @Test
    public void testSetArrivalCityFailure() {
        String arrivalCity = null;
        flight.setArrivalCity(arrivalCity);
        assertEquals("Arrival city should be null", arrivalCity, flight.getArrivalCity());
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSetArrivalCityException() {
        String arrivalCity = "";
        flight.setArrivalCity(arrivalCity);
    }
}
