// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_setOperatingAirlines_cb684284a9_Test {

    @InjectMocks
    private Flight flight;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetOperatingAirlines_success() {
        String expectedOperatingAirlines = "Test Airlines";
        flight.setOperatingAirlines(expectedOperatingAirlines);
        assertEquals(expectedOperatingAirlines, flight.getOperatingAirlines());
    }

    @Test
    public void testSetOperatingAirlines_null() {
        String expectedOperatingAirlines = null;
        flight.setOperatingAirlines(expectedOperatingAirlines);
        assertEquals(expectedOperatingAirlines, flight.getOperatingAirlines());
    }

    @Test
    public void testSetOperatingAirlines_emptyString() {
        String expectedOperatingAirlines = "";
        flight.setOperatingAirlines(expectedOperatingAirlines);
        assertEquals(expectedOperatingAirlines, flight.getOperatingAirlines());
    }
}
