// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.sql.Timestamp;
import java.util.Date;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_getEstimatedDepartureTime_2bcaac11d4_Test {

    private Flight flight;

    @BeforeEach
    public void setup() {
        flight = Mockito.mock(Flight.class);
    }

    @Test
    public void testGetEstimatedDepartureTime() {
        Timestamp expectedTimestamp = new Timestamp(new Date().getTime());
        Mockito.when(flight.getEstimatedDepartureTime()).thenReturn(expectedTimestamp);

        Timestamp actualTimestamp = flight.getEstimatedDepartureTime();

        assertEquals(expectedTimestamp, actualTimestamp);
    }

    @Test
    public void testGetEstimatedDepartureTime_Null() {
        Mockito.when(flight.getEstimatedDepartureTime()).thenReturn(null);

        Timestamp actualTimestamp = flight.getEstimatedDepartureTime();

        assertEquals(null, actualTimestamp);
    }
}
