// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_getOperatingAirlines_bfd144796e_Test {

    private Flight flight;

    @BeforeEach
    public void setup() {
        flight = new Flight();
    }

    @Test
    public void testGetOperatingAirlines_Success() {
        // TODO: replace "Airline1" with the actual operating airline
        flight.setOperatingAirlines("Airline1");
        String expected = "Airline1";
        String actual = flight.getOperatingAirlines();
        assertEquals(expected, actual);
    }

    @Test
    public void testGetOperatingAirlines_Null() {
        // TODO: replace null with the actual operating airline
        flight.setOperatingAirlines(null);
        String expected = null;
        String actual = flight.getOperatingAirlines();
        assertEquals(expected, actual);
    }
}
