// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_getFlightNumber_a56f113b8e_Test {
    private Flight flight;

    @BeforeEach
    public void setup() {
        flight = new Flight();
    }

    @Test
    public void testGetFlightNumber_WhenFlightNumberIsSet_ShouldReturnSameFlightNumber() {
        String flightNumber = "FR1234";
        flight.setFlightNumber(flightNumber);
        
        assertEquals(flightNumber, flight.getFlightNumber(), "Expected flight number to be " + flightNumber);
    }

    @Test
    public void testGetFlightNumber_WhenFlightNumberIsNotSet_ShouldReturnNull() {
        assertEquals(null, flight.getFlightNumber(), "Expected flight number to be null as it is not set yet");
    }
}
