// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

public class Flight_getDepartureCity_5815b8a6c4_Test {

    private Flight flight;

    @Before
    public void setUp() {
        flight = Mockito.mock(Flight.class);
    }

    @Test
    public void testGetDepartureCity_Success() {
        String expectedDepartureCity = "New York";
        Mockito.when(flight.getDepartureCity()).thenReturn(expectedDepartureCity);
        String actualDepartureCity = flight.getDepartureCity();
        Assert.assertEquals(expectedDepartureCity, actualDepartureCity);
    }

    @Test
    public void testGetDepartureCity_Failure() {
        String unexpectedDepartureCity = "Los Angeles";
        Mockito.when(flight.getDepartureCity()).thenReturn("New York");
        String actualDepartureCity = flight.getDepartureCity();
        Assert.assertNotEquals(unexpectedDepartureCity, actualDepartureCity);
    }

}
