// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Flight_getArrivalCity_0aaf38c02c_Test {

    private Flight flight;

    @BeforeEach
    public void setUp() {
        flight = new Flight();
    }

    @Test
    public void testGetArrivalCity_Success() {
        String expectedCity = "New York";
        flight.setArrivalCity(expectedCity);
        String actualCity = flight.getArrivalCity();
        assertEquals(expectedCity, actualCity, "Arrival city should be New York");
    }

    @Test
    public void testGetArrivalCity_Failure() {
        String expectedCity = "Los Angeles";
        flight.setArrivalCity("New York");
        String actualCity = flight.getArrivalCity();
        assertEquals(expectedCity, actualCity, "Arrival city should be Los Angeles");
    }

    @Test
    public void testGetArrivalCity_Null() {
        String expectedCity = null;
        flight.setArrivalCity(expectedCity);
        String actualCity = flight.getArrivalCity();
        assertEquals(expectedCity, actualCity, "Arrival city should be null");
    }
}
