// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;

class Flight_setOperatingAirlines_720a951151_Test {

    @InjectMocks
    private Flight flight;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetOperatingAirlines_Success() {
        String expectedAirlines = "Air India";
        flight.setOperatingAirlines(expectedAirlines);
        assertEquals(expectedAirlines, flight.getOperatingAirlines());
    }

    @Test
    public void testSetOperatingAirlines_Failure() {
        String expectedAirlines = "Air India";
        flight.setOperatingAirlines("Emirates");
        assertNotEquals(expectedAirlines, flight.getOperatingAirlines());
    }

    @Test
    public void testSetOperatingAirlines_Null() {
        flight.setOperatingAirlines(null);
        assertNull(flight.getOperatingAirlines());
    }

    @Test
    public void testSetOperatingAirlines_Empty() {
        flight.setOperatingAirlines("");
        assertEquals("", flight.getOperatingAirlines());
    }
}
