// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Flight_getOperatingAirlines_9bd90a2957_Test {

    private Flight flight;

    @BeforeEach
    public void setUp() {
        flight = new Flight();
    }

    @Test
    public void testGetOperatingAirlinesWhenValueIsSet() {
        String expectedOperatingAirlines = "Airline1";
        flight.setOperatingAirlines(expectedOperatingAirlines);

        String actualOperatingAirlines = flight.getOperatingAirlines();

        assertEquals(expectedOperatingAirlines, actualOperatingAirlines);
    }

    @Test
    public void testGetOperatingAirlinesWhenValueIsNotSet() {
        String expectedOperatingAirlines = null;

        String actualOperatingAirlines = flight.getOperatingAirlines();

        assertEquals(expectedOperatingAirlines, actualOperatingAirlines);
    }
}
