// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;

public class Flight_getArrivalCity_a331c2c645_Test {

    @InjectMocks
    private Flight flight;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        flight = new Flight();
    }

    @Test
    public void testGetArrivalCity_success() {
        String expectedCity = "New York";
        flight.setArrivalCity(expectedCity);
        String actualCity = flight.getArrivalCity();
        assertEquals(expectedCity, actualCity, "The expected city should match the actual city");
    }

    @Test
    public void testGetArrivalCity_null() {
        flight.setArrivalCity(null);
        String actualCity = flight.getArrivalCity();
        assertNull(actualCity, "The actual city should be null");
    }
}
