// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import java.sql.Timestamp;
import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

// TODO: Replace with your actual class name
@Entity
public class Flight {
    private Timestamp estimatedDepartureTime;

    public void setEstimatedDepartureTime(Timestamp estimatedDepartureTime) {
        this.estimatedDepartureTime = estimatedDepartureTime;
    }

    public Timestamp getEstimatedDepartureTime() {
        return estimatedDepartureTime;
    }
}

public class Flight_setEstimatedDepartureTime_37ed1a5239_Test {

    private Flight flight;

    @BeforeEach
    public void setup() {
        flight = new Flight();
    }

    @Test
    public void testSetEstimatedDepartureTime() {
        Timestamp timestamp = new Timestamp(new Date().getTime());
        flight.setEstimatedDepartureTime(timestamp);
        assertEquals(timestamp, flight.getEstimatedDepartureTime());
    }

    @Test
    public void testSetEstimatedDepartureTime_null() {
        flight.setEstimatedDepartureTime(null);
        assertEquals(null, flight.getEstimatedDepartureTime());
    }
}
