// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import java.sql.Timestamp;
import java.util.Date;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;

@Entity
public class Flight_getDateOfDeparture_8146d4e325_Test {

    private Flight flight;
    private Date mockDate;

    @BeforeEach
    public void setup() {
        flight = Mockito.mock(Flight.class);
        mockDate = new Timestamp(System.currentTimeMillis());
    }

    @Test
    public void testGetDateOfDeparture() {
        Mockito.when(flight.getDateOfDeparture()).thenReturn(mockDate);
        Date result = flight.getDateOfDeparture();
        assertEquals(mockDate, result, "Expected and actual departure dates should match");
    }

    @Test
    public void testGetDateOfDeparture_nullDate() {
        Mockito.when(flight.getDateOfDeparture()).thenReturn(null);
        Date result = flight.getDateOfDeparture();
        assertEquals(null, result, "Expected and actual departure dates should match when date is null");
    }
}
