// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Before;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.Assert.assertEquals;

public class Passenger_toString_ceffa8036e_Test {

    @InjectMocks
    private Passenger passenger;

    @Before
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testToStringWithAllFields() {
        passenger.setFirstName("John");
        passenger.setMiddleName("D");
        passenger.setLastName("Doe");
        passenger.setEmail("john.doe@example.com");
        passenger.setPhone("1234567890");

        String result = passenger.toString();
        assertEquals("Passenger{firstName='John', middleName='D', lastName='Doe', email='john.doe@example.com', phone='1234567890'}", result);
    }

    @Test
    public void testToStringWithMissingFields() {
        passenger.setFirstName("John");
        passenger.setLastName("Doe");
        passenger.setEmail("john.doe@example.com");

        String result = passenger.toString();
        assertEquals("Passenger{firstName='John', middleName='null', lastName='Doe', email='john.doe@example.com', phone='null'}", result);
    }
}
