// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_getMiddleName_1fb9604eaa_Test {

    private Passenger passenger;

    @BeforeEach
    public void setup() {
        passenger = new Passenger();
    }

    @Test
    public void testGetMiddleName_WhenMiddleNameIsSet() {
        String expectedMiddleName = "John";
        passenger.setMiddleName(expectedMiddleName);
        String actualMiddleName = passenger.getMiddleName();
        assertEquals(expectedMiddleName, actualMiddleName, "Middle name should be John");
    }

    @Test
    public void testGetMiddleName_WhenMiddleNameIsNotSet() {
        String actualMiddleName = passenger.getMiddleName();
        assertEquals(null, actualMiddleName, "Middle name should be null as it is not set");
    }
}
