// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_toString_2393b88875_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testToString() {
        passenger.setFirstName("John");
        passenger.setMiddleName("Doe");
        passenger.setLastName("Smith");
        passenger.setEmail("john.doe@gmail.com");
        passenger.setPhone("1234567890");

        String expectedOutput = "Passenger{" +
                "firstName='John'" +
                ", middleName='Doe'" +
                ", lastName='Smith'" +
                ", email='john.doe@gmail.com'" +
                ", phone='1234567890'" +
                '}';

        assertEquals(expectedOutput, passenger.toString());
    }

    @Test
    public void testToStringWithNullValues() {
        passenger.setFirstName(null);
        passenger.setMiddleName(null);
        passenger.setLastName(null);
        passenger.setEmail(null);
        passenger.setPhone(null);

        String expectedOutput = "Passenger{" +
                "firstName='null'" +
                ", middleName='null'" +
                ", lastName='null'" +
                ", email='null'" +
                ", phone='null'" +
                '}';

        assertEquals(expectedOutput, passenger.toString());
    }
}
