// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class Passenger_setPhone_fec6a16ac9_Test {

    @Mock
    private Passenger passenger;

    @Before
    public void setUp() {
        when(passenger.getPhone()).thenReturn("1234567890");
    }

    @Test
    public void testSetPhone_Success() {
        passenger.setPhone("0987654321");
        assertEquals("Phone number should match", "0987654321", passenger.getPhone());
    }

    @Test
    public void testSetPhone_Failure() {
        passenger.setPhone("invalid phone number");
        assertEquals("Phone number should match", "1234567890", passenger.getPhone());
    }
}
