// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_getEmail_7b79ef55db_Test {

    private Passenger passenger;

    @BeforeEach
    public void setup() {
        passenger = new Passenger();
    }

    @Test
    public void testGetEmail_Success() {
        String expectedEmail = "test@example.com";
        passenger.setEmail(expectedEmail);
        String actualEmail = passenger.getEmail();
        assertEquals(expectedEmail, actualEmail);
    }

    @Test
    public void testGetEmail_Null() {
        String expectedEmail = null;
        passenger.setEmail(expectedEmail);
        String actualEmail = passenger.getEmail();
        assertEquals(expectedEmail, actualEmail);
    }
}
