// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Passenger_setMiddleName_64fb9e3fba_Test {

    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        passenger = new Passenger();
    }

    @Test
    public void testSetMiddleName_Success() {
        String middleName = "James";
        passenger.setMiddleName(middleName);
        assertEquals(middleName, passenger.getMiddleName());
    }

    @Test
    public void testSetMiddleName_Null() {
        String middleName = null;
        passenger.setMiddleName(middleName);
        assertEquals(middleName, passenger.getMiddleName());
    }
}
