// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Passenger_getPhone_39409e28ac_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPhone_success() {
        String expectedPhone = "123-456-7890";
        when(passenger.getPhone()).thenReturn(expectedPhone);

        String actualPhone = passenger.getPhone();

        assertEquals(expectedPhone, actualPhone, "Phone numbers should match");
    }

    @Test
    public void testGetPhone_empty() {
        String expectedPhone = "";
        when(passenger.getPhone()).thenReturn(expectedPhone);

        String actualPhone = passenger.getPhone();

        assertEquals(expectedPhone, actualPhone, "Phone numbers should match");
    }
}
