// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Passenger_getMiddleName_e4a286331a_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetMiddleName_WhenMiddleNameIsPresent() {
        when(passenger.getMiddleName()).thenReturn("John");

        String middleName = passenger.getMiddleName();

        assertEquals("John", middleName, "The middle name should be John");
    }

    @Test
    public void testGetMiddleName_WhenMiddleNameIsNull() {
        when(passenger.getMiddleName()).thenReturn(null);

        String middleName = passenger.getMiddleName();

        assertEquals(null, middleName, "The middle name should be null");
    }
}
