// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_getFirstName_0d799bf2a4_Test {

    @InjectMocks
    private Passenger passenger;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetFirstName() {
        String expectedFirstName = "John";
        passenger.setFirstName(expectedFirstName);
        String actualFirstName = passenger.getFirstName();
        assertEquals(expectedFirstName, actualFirstName);
    }

    @Test
    public void testGetFirstNameWhenFirstNameIsNull() {
        passenger.setFirstName(null);
        String actualFirstName = passenger.getFirstName();
        assertEquals(null, actualFirstName);
    }
}
