// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SpringExtension.class)
public class Passenger_getFirstName_94e06d272a_Test {

    @InjectMocks
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetFirstName() {
        String expectedFirstName = "John";
        passenger.setFirstName(expectedFirstName);
        String actualFirstName = passenger.getFirstName();
        assertEquals(expectedFirstName, actualFirstName);
    }

    @Test
    public void testGetFirstNameWithNull() {
        passenger.setFirstName(null);
        String actualFirstName = passenger.getFirstName();
        assertEquals(null, actualFirstName);
    }
}
