// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Passenger_setFirstName_f9bf7d9c2d_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetFirstName_ValidName() {
        String expectedFirstName = "John";
        passenger.setFirstName(expectedFirstName);
        assertEquals(expectedFirstName, passenger.getFirstName(), "The first name should be set correctly");
    }

    @Test
    public void testSetFirstName_NullName() {
        String expectedFirstName = null;
        assertThrows(NullPointerException.class, () -> passenger.setFirstName(expectedFirstName), "The first name should not be null");
    }
}
