// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.Assert.assertEquals;

@SpringBootTest
@RunWith(MockitoJUnitRunner.class)
public class Passenger_setLastName_815ee71c38_Test {

    @Test
    public void testSetLastName_ValidLastName() {
        Passenger passenger = new Passenger();
        String expectedLastName = "Smith";
        passenger.setLastName(expectedLastName);
        assertEquals("The last name should be Smith", expectedLastName, passenger.getLastName());
    }
    
    @Test
    public void testSetLastName_NullLastName() {
        Passenger passenger = new Passenger();
        passenger.setLastName(null);
        assertEquals("The last name should be null", null, passenger.getLastName());
    }

    @Test
    public void testSetLastName_EmptyLastName() {
        Passenger passenger = new Passenger();
        String expectedLastName = "";
        passenger.setLastName(expectedLastName);
        assertEquals("The last name should be an empty string", expectedLastName, passenger.getLastName());
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSetLastName_InvalidLastName() {
        Passenger passenger = new Passenger();
        passenger.setLastName("Smith123"); // TODO: Change the value to a valid last name
    }
}
