// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_setPhone_eaff40e9dc_Test {

    private Passenger passenger;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        passenger = new Passenger();
    }

    @Test
    public void testSetPhone_success() {
        String expectedPhone = "123-456-7890";
        passenger.setPhone(expectedPhone);
        assertEquals(expectedPhone, passenger.getPhone());
    }

    @Test
    public void testSetPhone_null() {
        String expectedPhone = null;
        passenger.setPhone(expectedPhone);
        assertEquals(expectedPhone, passenger.getPhone());
    }
}
