// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_setLastName_4141db5e7c_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        passenger = new Passenger();
    }

    @Test
    public void testSetLastName() {
        String lastName = "Smith";
        passenger.setLastName(lastName);
        assertEquals(lastName, passenger.getLastName());
    }

    @Test
    public void testSetLastName_Null() {
        String lastName = null;
        passenger.setLastName(lastName);
        assertEquals(lastName, passenger.getLastName());
    }

    @Test
    public void testSetLastName_Empty() {
        String lastName = "";
        passenger.setLastName(lastName);
        assertEquals(lastName, passenger.getLastName());
    }
}
