// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_setEmail_d1f6d493ae_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        passenger = new Passenger();
    }

    @Test
    public void testSetEmailSuccess() {
        String email = "test@example.com";
        passenger.setEmail(email);
        assertEquals(email, passenger.getEmail());
    }

    @Test
    public void testSetEmailFailure() {
        String email = "invalid email";
        passenger.setEmail(email);
        assertEquals(null, passenger.getEmail());
    }
}
