// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.test.context.junit4.SpringRunner;
import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
public class Passenger_setEmail_8c969b78a8_Test {

    @InjectMocks
    private Passenger passenger;

    @Before
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetEmail_Success() {
        String email = "test@test.com";
        passenger.setEmail(email);
        assertEquals(email, passenger.getEmail());
    }

    @Test
    public void testSetEmail_Null() {
        String email = null;
        passenger.setEmail(email);
        assertEquals(email, passenger.getEmail());
    }
}
