// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_setFirstName_8acaec2cfc_Test {
    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        passenger = new Passenger();
    }

    @Test
    public void testSetFirstName_Success() {
        String expectedFirstName = "John";
        passenger.setFirstName(expectedFirstName);
        assertEquals(expectedFirstName, passenger.getFirstName());
    }

    @Test
    public void testSetFirstName_Null() {
        String expectedFirstName = null;
        passenger.setFirstName(expectedFirstName);
        assertEquals(expectedFirstName, passenger.getFirstName());
    }
}
