// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Passenger_getLastName_de1cc748dc_Test {

    @Mock
    private Passenger passenger;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetLastNameSuccess() {
        String expectedLastName = "Smith";
        Mockito.when(passenger.getLastName()).thenReturn(expectedLastName);
        String actualLastName = passenger.getLastName();
        Assertions.assertEquals(expectedLastName, actualLastName);
    }

    @Test
    public void testGetLastNameFailure() {
        String expectedLastName = "Johnson";
        Mockito.when(passenger.getLastName()).thenReturn("Smith");
        String actualLastName = passenger.getLastName();
        Assertions.assertNotEquals(expectedLastName, actualLastName);
    }
}
