// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_getLastName_4814a2dee7_Test {

    @InjectMocks
    private Passenger passenger;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetLastNameSuccess() {
        String expectedLastName = "Smith";
        passenger.setLastName(expectedLastName);
        String actualLastName = passenger.getLastName();
        assertEquals(expectedLastName, actualLastName, "The last names should match");
    }

    @Test
    public void testGetLastNameFailure() {
        String expectedLastName = "Johnson";
        passenger.setLastName("Smith");
        String actualLastName = passenger.getLastName();
        assertEquals(expectedLastName, actualLastName, "The last names should not match");
    }
}
