// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_getEmail_7bf7b35375_Test {

    private Passenger passenger;

    @BeforeEach
    public void setUp() {
        passenger = new Passenger();
    }

    @Test
    public void testGetEmail_ValidEmail() {
        String expectedEmail = "test@gmail.com";
        passenger.setEmail(expectedEmail);
        String actualEmail = passenger.getEmail();
        assertEquals(expectedEmail, actualEmail, "The expected email does not match the actual email");
    }

    @Test
    public void testGetEmail_EmptyEmail() {
        String expectedEmail = "";
        passenger.setEmail(expectedEmail);
        String actualEmail = passenger.getEmail();
        assertEquals(expectedEmail, actualEmail, "The expected email does not match the actual email");
    }

    @Test
    public void testGetEmail_NullEmail() {
        String expectedEmail = null;
        passenger.setEmail(expectedEmail);
        String actualEmail = passenger.getEmail();
        assertEquals(expectedEmail, actualEmail, "The expected email does not match the actual email");
    }
}
