// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Passenger_getPhone_cc9306d4c7_Test {

    @InjectMocks
    private Passenger passenger;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        passenger.setPhone("1234567890"); // TODO: Change the phone number as per your test data
    }

    @Test
    public void testGetPhone_success() {
        String expectedPhone = "1234567890"; // TODO: Change the expected phone number as per your test data
        String actualPhone = passenger.getPhone();
        assertEquals(expectedPhone, actualPhone, "The expected phone number does not match the actual phone number");
    }

    @Test
    public void testGetPhone_failure() {
        String expectedPhone = "0987654321"; // TODO: Change the expected phone number as per your test data
        String actualPhone = passenger.getPhone();
        assertEquals(expectedPhone, actualPhone, "The expected phone number does not match the actual phone number");
    }
}
