// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class Reservation_setNumberOfBags_5d8de57ae8_Test {

    @InjectMocks
    private Reservation reservation;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetNumberOfBags_PositiveNumber() {
        int numberOfBags = 2;
        reservation.setNumberOfBags(numberOfBags);
        Assertions.assertEquals(numberOfBags, reservation.getNumberOfBags());
    }

    @Test
    public void testSetNumberOfBags_Zero() {
        int numberOfBags = 0;
        reservation.setNumberOfBags(numberOfBags);
        Assertions.assertEquals(numberOfBags, reservation.getNumberOfBags());
    }

    @Test
    public void testSetNumberOfBags_NegativeNumber() {
        int numberOfBags = -1;
        // TODO: Update this value to a valid number of bags
        Assertions.assertThrows(IllegalArgumentException.class, () -> reservation.setNumberOfBags(numberOfBags));
    }
}
