// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.Entity;
import javax.persistence.OneToOne;

@Entity
class Flight {
    // TODO: Define flight properties
}

@Entity
class Reservation {
    @OneToOne
    private Flight flight;

    public void setFlight(Flight flight) {
        this.flight = flight;
    }

    public Flight getFlight() {
        return this.flight;
    }
}

public class Reservation_setFlight_c17b20b503_Test {

    @InjectMocks
    Reservation reservation;

    @Mock
    Flight flight;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetFlight() {
        reservation.setFlight(flight);
        assertEquals(flight, reservation.getFlight());
    }

    @Test
    public void testSetFlightWithNull() {
        reservation.setFlight(null);
        assertEquals(null, reservation.getFlight());
    }
}
