// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class Reservation_setPassenger_c2b9d64f65_Test {

    @Mock
    private Passenger passenger;

    @InjectMocks
    private Reservation reservation;

    @BeforeEach
    public void setUp() {
        reservation = new Reservation();
    }

    @Test
    public void testSetPassenger() {
        reservation.setPassenger(passenger);
        assertEquals(passenger, reservation.getPassenger());
    }

    @Test
    public void testSetPassenger_Null() {
        reservation.setPassenger(null);
        assertEquals(null, reservation.getPassenger());
    }
}
