// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Reservation_setCheckedin_c5c5ddf8b6_Test {

    private Reservation reservation;

    @BeforeEach
    public void setup() {
        reservation = new Reservation();
    }

    @Test
    public void testSetCheckedInTrue() {
        reservation.setCheckedin(true);
        assertEquals(true, reservation.isCheckedIn(), "The checked in status should be true");
    }

    @Test
    public void testSetCheckedInFalse() {
        reservation.setCheckedin(false);
        assertEquals(false, reservation.isCheckedIn(), "The checked in status should be false");
    }
}
