// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;

@Entity
public class Reservation_setPassenger_c2b9d64f65_Test {

    private Reservation reservation;
    private Passenger mockPassenger;

    @BeforeEach
    public void setUp() {
        reservation = new Reservation();
        mockPassenger = Mockito.mock(Passenger.class);
    }

    @Test
    public void testSetPassenger_Success() {
        // Given a mock passenger
        Mockito.when(mockPassenger.getName()).thenReturn("John Doe");

        // When setPassenger is called
        reservation.setPassenger(mockPassenger);

        // Then the passenger should be set correctly
        assertEquals("John Doe", reservation.getPassenger().getName());
    }

    @Test
    public void testSetPassenger_Null() {
        // When setPassenger is called with null
        reservation.setPassenger(null);

        // Then the passenger should be null
        assertEquals(null, reservation.getPassenger());
    }
}
