// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;

@Entity
public class Reservation_toString_2393b88875_Test {

    private Reservation reservation;
    private Passenger passenger;
    private Flight flight;

    @BeforeEach
    public void setup() {
        passenger = mock(Passenger.class);
        flight = mock(Flight.class);
        reservation = new Reservation();
        reservation.setPassenger(passenger);
        reservation.setFlight(flight);
    }

    @Test
    public void testToStringWithCheckedInAndBags() {
        reservation.setCheckedIn(true);
        reservation.setNumberOfBags(2);
        String expected = "Reservation{checkedin=true, numberOfBags=2, passenger=" + passenger + ", flight=" + flight + "}";
        assertEquals(expected, reservation.toString());
    }

    @Test
    public void testToStringWithoutCheckedInAndBags() {
        reservation.setCheckedIn(false);
        reservation.setNumberOfBags(0);
        String expected = "Reservation{checkedin=false, numberOfBags=0, passenger=" + passenger + ", flight=" + flight + "}";
        assertEquals(expected, reservation.toString());
    }
}
