// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

@Entity
public class Reservation_getFlight_9ec9cadc6c_Test {

    @OneToOne
    @Mock
    Flight flight;

    @InjectMocks
    Reservation reservation;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetFlight() {
        Flight testFlight = new Flight();
        testFlight.setFlightNumber("A123");
        when(flight.getFlightNumber()).thenReturn("A123");

        reservation.setFlight(testFlight);
        Flight resultFlight = reservation.getFlight();

        assertEquals(testFlight.getFlightNumber(), resultFlight.getFlightNumber());
    }

    @Test
    public void testGetFlight_NoFlightSet() {
        Flight resultFlight = reservation.getFlight();

        assertEquals(null, resultFlight);
    }
}
