// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

@Entity
public class Reservation_getNumberOfBags_4e8beb8ff5_Test {

    private Reservation reservation;

    @BeforeEach
    public void setUp() {
        reservation = Mockito.mock(Reservation.class);
    }

    @Test
    public void testGetNumberOfBags_WithValidInput() {
        Mockito.when(reservation.getNumberOfBags()).thenReturn(2);

        int result = reservation.getNumberOfBags();
        assertEquals(2, result, "The number of bags should be 2");
    }

    @Test
    public void testGetNumberOfBags_WithNoBags() {
        Mockito.when(reservation.getNumberOfBags()).thenReturn(0);

        int result = reservation.getNumberOfBags();
        assertEquals(0, result, "The number of bags should be 0");
    }
}
