// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Reservation_getPassenger_dd171db682_Test {

    @Mock
    private Reservation reservation;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetPassenger_Success() {
        Passenger mockPassenger = new Passenger();
        mockPassenger.setName("John Doe");
        when(reservation.getPassenger()).thenReturn(mockPassenger);

        Passenger result = reservation.getPassenger();
        assertEquals("John Doe", result.getName());
    }

    @Test
    public void testGetPassenger_Null() {
        when(reservation.getPassenger()).thenReturn(null);

        Passenger result = reservation.getPassenger();
        assertEquals(null, result);
    }
}
