// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.*;

public class Reservation_setCheckedin_058d5c714d_Test {

    @Mock
    private Reservation reservation;

    @BeforeEach
    public void setUp() throws Exception {
        MockitoAnnotations.initMocks(this);
        reservation = new Reservation();
    }

    @Test
    public void testSetCheckedInTrue() {
        reservation.setCheckedin(true);
        assertTrue(reservation.isCheckedIn());
    }

    @Test
    public void testSetCheckedInFalse() {
        reservation.setCheckedin(false);
        assertFalse(reservation.isCheckedIn());
    }
}
