// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class Reservation_isCheckedin_519916c3a0_Test {

    @InjectMocks
    private Reservation reservation;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsCheckedInTrue() {
        reservation.setCheckedIn(true);
        assertTrue(reservation.isCheckedin());
    }

    @Test
    public void testIsCheckedInFalse() {
        reservation.setCheckedIn(false);
        assertFalse(reservation.isCheckedin());
    }
}
