// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

@SpringBootTest
public class Role_getName_4ad76af4d7_Test {

    @MockBean
    private Role role;

    @BeforeEach
    public void setUp() {
        Mockito.when(role.getName()).thenReturn("Admin");
    }

    @Test
    public void testGetNameSuccess() {
        // TODO: Change the value "Admin" to the expected value
        String expectedName = "Admin";
        String actualName = role.getName();
        assertEquals(expectedName, actualName, "The expected name does not match the actual name");
    }

    @Test
    public void testGetNameFailure() {
        // TODO: Change the value "User" to a value different from the expected one
        String unexpectedName = "User";
        String actualName = role.getName();
        assertNotEquals(unexpectedName, actualName, "The unexpected name matches the actual name");
    }
}
