// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
public class Role_setName_f5bd015150_Test {

    @MockBean
    private Role role;

    @BeforeEach
    public void setUp() {
        role = new Role();
    }

    @Test
    public void testSetName_Success() {
        String expectedName = "Admin";
        role.setName(expectedName);
        assertEquals(expectedName, role.getName());
    }

    @Test
    public void testSetName_Null() {
        String expectedName = null;
        role.setName(expectedName);
        assertNull(role.getName());
    }

    @Test
    public void testSetName_EmptyString() {
        String expectedName = "";
        role.setName(expectedName);
        assertEquals(expectedName, role.getName());
    }
}
