// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Role_toString_2393b88875_Test {

    private Role role;

    @BeforeEach
    public void setUp() {
        role = Mockito.mock(Role.class);
    }

    @Test
    public void testToString() {
        Mockito.when(role.toString()).thenReturn("Role{name='Admin'}");
        String result = role.toString();
        assertEquals("Role{name='Admin'}", result);
    }

    @Test
    public void testToString_Empty() {
        Mockito.when(role.toString()).thenReturn("Role{name=''}");
        String result = role.toString();
        assertEquals("Role{name=''}", result);
    }
}
