// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.springframework.security.core.GrantedAuthority;

public class Role_getAuthority_e3f8673213_Test {

    @Test
    public void testGetAuthority() {
        // Create a mock Role object
        Role role = new Role();
        role.setName("ROLE_ADMIN");

        // Check if getAuthority returns the correct authority
        assertEquals("ROLE_ADMIN", role.getAuthority());
    }

    @Test
    public void testGetAuthorityWhenNameIsNull() {
        // Create a mock Role object with null name
        Role role = new Role();
        role.setName(null);

        // Check if getAuthority returns null when name is null
        assertEquals(null, role.getAuthority());
    }
}
