// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.core.GrantedAuthority;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

@ExtendWith(MockitoExtension.class)
public class Role_setUsers_f8e8a44741_Test {

    @InjectMocks
    private Role role;

    private Set<User> users;

    @BeforeEach
    public void setUp() {
        users = new HashSet<>();
        User user1 = new User();
        user1.setUsername("user1");
        users.add(user1);

        User user2 = new User();
        user2.setUsername("user2");
        users.add(user2);
    }

    @Test
    public void testSetUsers() {
        role.setUsers(users);
        Set<User> actualUsers = role.getUsers();
        assertNotNull(actualUsers);
        assertEquals(users, actualUsers);
    }

    @Test
    public void testSetUsersWithNull() {
        role.setUsers(null);
        Set<User> actualUsers = role.getUsers();
        assertEquals(null, actualUsers);
    }
}
