// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;

public class User_setLastName_815ee71c38_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = new User();
    }

    @Test
    public void testSetLastName() {
        String lastName = "Doe";
        user.setLastName(lastName);
        Assertions.assertEquals(lastName, user.getLastName());
    }

    @Test
    public void testSetLastNameNull() {
        String lastName = null;
        user.setLastName(lastName);
        Assertions.assertNull(user.getLastName());
    }

    @Test
    public void testSetLastNameEmpty() {
        String lastName = "";
        user.setLastName(lastName);
        Assertions.assertEquals(lastName, user.getLastName());
    }
}
