// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class User_toString_2393b88875_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = new User();
    }

    @Test
    public void testToString() {
        user.setFirstName("John");
        user.setLastName("Doe");
        user.setEmail("john.doe@example.com");
        user.setPassword("password123");

        String expected = "User{firstName='John', lastName='Doe', email='john.doe@example.com', password='password123'}";
        String actual = user.toString();

        assertEquals(expected, actual);
    }

    @Test
    public void testToStringWithEmptyFields() {
        user.setFirstName("");
        user.setLastName("");
        user.setEmail("");
        user.setPassword("");

        String expected = "User{firstName='', lastName='', email='', password=''}";
        String actual = user.toString();

        assertEquals(expected, actual);
    }
}
