// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class User_setRoles_95de437192_Test {
    @Mock
    private User user;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetRoles() {
        Set<Role> roles = new HashSet<>();
        roles.add(new Role("ROLE_USER"));
        roles.add(new Role("ROLE_ADMIN"));

        when(user.getRoles()).thenReturn(roles);

        user.setRoles(roles);
        Set<Role> actualRoles = user.getRoles();

        assertEquals(roles, actualRoles);
    }

    @Test
    public void testSetRolesWithEmptySet() {
        Set<Role> roles = new HashSet<>();

        when(user.getRoles()).thenReturn(roles);

        user.setRoles(roles);
        Set<Role> actualRoles = user.getRoles();

        assertEquals(roles, actualRoles);
    }
}
