// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class User_getRoles_1b4014bde2_Test {

    @InjectMocks
    User user;

    @Mock
    Set<Role> roles;

    @Before
    public void setUp() {
        roles = new HashSet<>();
        roles.add(new Role("ADMIN"));
        roles.add(new Role("USER"));
        user = new User();
        user.setRoles(roles);
    }

    @Test
    public void testGetRolesSuccess() {
        when(user.getRoles()).thenReturn(roles);
        Set<Role> actualRoles = user.getRoles();
        assertEquals(roles, actualRoles);
    }

    @Test
    public void testGetRolesFailure() {
        Set<Role> wrongRoles = new HashSet<>();
        wrongRoles.add(new Role("GUEST"));
        when(user.getRoles()).thenReturn(roles);
        Set<Role> actualRoles = user.getRoles();
        assertNotEquals(wrongRoles, actualRoles);
    }
}
