// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
class User_setEmail_8c969b78a8_Test {

    private User user;

    @BeforeEach
    void setUp() {
        user = new User();
    }

    @Test
    public void testSetEmail() {
        String expectedEmail = "test@example.com";
        user.setEmail(expectedEmail);
        assertEquals(expectedEmail, user.getEmail());
    }

    @Test
    public void testSetEmailWithEmpty() {
        String expectedEmail = "";
        user.setEmail(expectedEmail);
        assertEquals(expectedEmail, user.getEmail());
    }
}
