// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class User_setFirstName_f9bf7d9c2d_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = new User();
    }

    @Test
    public void testSetFirstName_validFirstName() {
        String validFirstName = "John";
        user.setFirstName(validFirstName);
        assertEquals(validFirstName, user.getFirstName(), "Expected firstName to be set correctly");
    }

    @Test
    public void testSetFirstName_emptyFirstName() {
        String emptyFirstName = "";
        user.setFirstName(emptyFirstName);
        assertEquals(emptyFirstName, user.getFirstName(), "Expected firstName to be set even when it's empty");
    }

    @Test
    public void testSetFirstName_nullFirstName() {
        user.setFirstName(null);
        assertEquals(null, user.getFirstName(), "Expected firstName to be set to null");
    }
}
