// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class User_getFirstName_0d799bf2a4_Test {

    private User user;

    @BeforeEach
    public void setUp() {
        user = new User();
    }

    @Test
    public void testGetFirstName_WhenFirstNameIsSet() {
        String expectedFirstName = "John";
        user.setFirstName(expectedFirstName);
        String actualFirstName = user.getFirstName();
        assertEquals(expectedFirstName, actualFirstName, "The first name should be John");
    }

    @Test
    public void testGetFirstName_WhenFirstNameIsNotSet() {
        String expectedFirstName = null;
        String actualFirstName = user.getFirstName();
        assertEquals(expectedFirstName, actualFirstName, "The first name should be null as it is not set yet");
    }
}
