// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class User_setPassword_94ccb89d82_Test {

    @InjectMocks
    private User user;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testSetPassword_validPassword() {
        String password = "validPassword123";
        user.setPassword(password);
        assertEquals(password, user.getPassword());
    }

    @Test
    public void testSetPassword_nullPassword() {
        String password = null;
        assertThrows(NullPointerException.class, () -> user.setPassword(password));
    }

    @Test
    public void testSetPassword_emptyPassword() {
        String password = "";
        user.setPassword(password);
        assertEquals(password, user.getPassword());
    }
}
