// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.domains;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class User_getEmail_7bf7b35375_Test {
    private User user;

    @BeforeEach
    public void setup() {
        user = new User();
    }

    @Test
    public void testGetEmail_Success() {
        String expectedEmail = "test@example.com";
        user.setEmail(expectedEmail);
        String actualEmail = user.getEmail();
        assertEquals(expectedEmail, actualEmail, "Email should match the set value");
    }

    @Test
    public void testGetEmail_Null() {
        String expectedEmail = null;
        user.setEmail(expectedEmail);
        String actualEmail = user.getEmail();
        assertEquals(expectedEmail, actualEmail, "Email should be null when not set");
    }
}
