// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.exceptions;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ResponseStatus(value = HttpStatus.NOT_FOUND)
public class FlightNotFound extends RuntimeException {
    public FlightNotFound(String exception) {
        super(exception);
    }
}

class FlightNotFoundTest {

    private FlightNotFound flightNotFound;

    @BeforeEach
    public void setUp() {
        flightNotFound = new FlightNotFound("Flight not found");
    }

    @Test
    public void testFlightNotFoundException() {
        assertEquals("Flight not found", flightNotFound.getMessage());
    }

    @Test
    public void testFlightNotFoundExceptionEmptyMessage() {
        FlightNotFound emptyException = new FlightNotFound("");
        assertEquals("", emptyException.getMessage());
    }
}
