// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.exceptions;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
public class TicketNotFound_TicketNotFound_d4b7aa247f_Test {

    private TicketNotFound ticketNotFound;

    @BeforeEach
    public void setUp() {
        ticketNotFound = null;
    }

    @Test
    public void testTicketNotFound_withMessage() {
        String message = "Ticket not found";
        ticketNotFound = new TicketNotFound(message);
        assertNotNull(ticketNotFound);
        assertEquals(message, ticketNotFound.getMessage());
    }

    @Test
    public void testTicketNotFound_withoutMessage() {
        String message = null;
        ticketNotFound = new TicketNotFound(message);
        assertNotNull(ticketNotFound);
        assertNull(ticketNotFound.getMessage());
    }
}
