// Test generated by RoostGPT for test flightReservation using AI Type Open AI and AI Model gpt-4

package com.flightreservation.flightreservation.exceptions;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ResponseStatus(value = HttpStatus.NOT_FOUND)
public class UserNotFound extends RuntimeException {
    public UserNotFound(String message) {
        super(message);
    }
}

class UserNotFound_UserNotFound_b9d9fbd545_Test {

    private UserNotFound userNotFound;

    @BeforeEach
    public void setup() {
        userNotFound = new UserNotFound("User not found");
    }

    @Test
    public void testUserNotFoundMessage() {
        assertEquals("User not found", userNotFound.getMessage());
    }

    @Test
    public void testUserNotFoundEmptyMessage() {
        UserNotFound userNotFoundEmpty = new UserNotFound("");
        assertEquals("", userNotFoundEmpty.getMessage());
    }
}
